---
title: "Data-analytic memos"
---

Over the quarter, you will write four "data-analytic memos" (DAMs). Each DAM will task you to use your newly-acquired data analysis skills. Many of the questions will be similar to what you may be asked to do on a future job (whether as an education researcher, analyst, or practitioner looking for evidence-based programming). You will also work with real-life education datasets. 

[^DAM]: "Following professors Andrew Ho and John Willett, I am calling these assignments “data-analytic memos,” which John Willett referred to fondly as “those DAM things.”

You need to show that you made a good faith effort to work each question. Mostly, I will grade your memos using a check system:

- ✔+: (*10 points*) Assignment is 100% completed. Every question was attempted and answered, and all answers are correct. Document is clean and easy to follow. Work is exceptional. 
- ✔: (*7 points*) Assignment is 70–99% complete and most answers are correct. 
- ✔−: (*4 points*) Assignment is less than 70% complete and/or many answers are incorrect. This indicates that you need to improve next time. I will hopefully not assign these often.

I will use these three levels as anchors, but may use the full ten-point range for your grade.

You may (and should!) work together on the DAMs, but *you must turn in your own answers.* You cannot work in groups of more than **three** people, and you must note who participated in the group in your assignment.

I will release the memos via Canvas, and you will submit your answers there.

In our class, you will learn how to describe your work verbally and communicate its findings. During week 10, you will meet with me one-on-one, in-person, to discuss your assignments and memos with me. I will provide more information about these meetings closer to our meeting. Half of your points for assignments and memos will rely on your written responses, and half of your points will reflect your ability to communicate your responses verbally. 
