---
title: Data
---

There are a ton of places to find data related to education, public policy, and administration (as well as data on pretty much any topic you want) online:

- [**Data is Plural newsletter**](https://www.data-is-plural.com/): Jeremy Singer-Vine sends a weekly newsletter of the most interesting public datasets he's found. You should subscribe to it. [He also has an archive of all the datasets he's highlighted.](https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit#gid=0)

- [**Google Dataset Search**](https://toolbox.google.com/datasetsearch): Google indexes thousands of public datasets; search for them here.

- [**J-PAL Catalog of Administrative Datasets**](https://www.povertyactionlab.org/catalog-administrative-data-sets): To assist researchers in screening potential data sources, J-PAL North America has cataloged a number of key US data sets.

- [**Kaggle**](https://www.kaggle.com/datasets): Kaggle hosts machine learning competitions where people compete to create the fastest, most efficient, most predictive algorithms. A byproduct of these competitions is a host of fascinating datasets that are generally free and open to the public. See, for example, [the European Soccer Database](https://www.kaggle.com/hugomathien/soccer), the [Salem Witchcraft Dataset](https://www.kaggle.com/rtatman/salem-witchcraft-dataset) or results from an [Oreo flavors taste test](https://www.kaggle.com/rtatman/oreo-flavors-tastetest-ratings).

- [**360Giving**](http://www.threesixtygiving.org/data/data-registry/): Dozens of British foundations follow a standard file format for sharing grant data and have made that data available online.

- [**US City Open Data Census**](http://us-cities.survey.okfn.org/): More than 100 US cities have committed to sharing dozens of types of data, including data about crime, budgets, campaign finance, lobbying, transit, and zoning. This site from the [Sunlight Foundation](http://sunlightfoundation.com/) and [Code for America](http://www.codeforamerica.org//) collects this data and rates cities by how well they're doing.

- [**The Stanford Education Data Archive (SEDA)**](https://exhibits.stanford.edu/data/catalog/db586ns4974) is "an initiative aimed at harnessing data to help us—scholars, policymakers, educators, parents—learn how to improve educational opportunity for all children."

- [**The Common Core of Data (CCD)**](https://nces.ed.gov/ccd/) is "the Department of Education's primary database on public elementary and secondary education in the United States".
  
- Data from large-scale assessments such as [**NAEP**](https://nces.ed.gov/nationsreportcard/researchcenter/software.aspx), [**PISA**](https://www.oecd.org/pisa/), and [**TIMSS**](https://nces.ed.gov/timss/) and [**PIRLS**](https://nces.ed.gov/surveys/pirls/).

- **Replication files**: Many academic journals now require that data (and code) be posted online, along with an article.   
    - **Journal websites**: If you read an academic article online, look for "supplemental materials" or the article's "data appendix". Here is a list of journals you may find helpful, many of which have adopted mandatory datasets/code deposits (or encourage them strongly). 
        - General interest journals, including [Nature](https://www.nature.com/nature/articles), and its partner journals [Nature Human Behaviour](https://www.nature.com/nathumbehav/) and [npj Science of Learning](https://www.nature.com/npjscilearn/), as well as [Science](https://www.science.org/journal/science), [PLoS One](https://journals.plos.org/plosone/), and [PNAS](https://www.pnas.org/)
        - Psychology journals, including [Psychological Science](https://journals.sagepub.com/home/pss), [Journal of Experimental Psychology](https://www.apa.org/pubs/journals/xge), and [Collabra](https://online.ucpress.edu/collabra) 
        - Education policy journals, including the [Journal of Research on Educational Effectiveness](https://www.tandfonline.com/journals/uree20) and [Educational Evaluation and Policy Analysis](https://journals.sagepub.com/home/epa)
        - Economics journals, including the [American Economic Review](https://www.aeaweb.org/journals/aer), [Quarterly Journal of Economics](https://academic.oup.com/qje), [AEJ: Applied Economics](https://www.aeaweb.org/journals/app), [AEJ: Economics Policy](https://www.aeaweb.org/journals/pol), [AER: Insights](https://www.aeaweb.org/journals/aeri), [Economic Journal](https://academic.oup.com/ej), [Journal of the European Economic Association](https://academic.oup.com/jeea), [Journal of Development Economics](https://www.sciencedirect.com/journal/journal-of-development-economics), and [Journal of Human Resources](https://jhr.uwpress.org/) 
    - [**Open Science Framework**](https://osf.io/): Many researchers use this platform to register their studies; some upload articles and datasets. The OSF website includes a [search function](https://osf.io/search) as well. 
    - The World Bank maintains a [Reproducible Research Repository](https://reproducibility.worldbank.org/index.php/home) with packages from its Policy Research Working Papers, journal articles, and reports. 
    - The [**AEA RCT Registry**](https://www.socialscienceregistry.org/) allows you to download [its metadata](https://dataverse.harvard.edu/dataverse/aearegistry)---that way, you can filter the Registry for any education experiments with publicly available data.  
    - [**Harvard Dataverse**](https://dataverse.harvard.edu/dataverse/harvard): This repository includes thousands of datasets from academic articles, including [the repository](https://dataverse.harvard.edu/dataverse/jpal) for articles by J-PAL affiliates.
    - Many researchers also post links to data and code on their websites---take a look at their lists of publications. [Here](https://de-barros.com/publication/) is mine. 
    
